---
title: "The Future of AI Agents"
subtitle: "Are Agents an Answer to Agency?"
author: "David Price"
date: "2026-06-30"
categories: [analysis, technology]
---

This article represents the view of the author and not ChatGPT, Gemini, Claude, Perplexity, or other artifical intelligence composition agents. The only "AI" used in its composition was a spell checker. If what follows is too sophmoric, the author acknowledges his background is in natural science not finance. His knowledge is limited to a collegic level course typically taken by second and third year students pursuing a university degree in finance. The author is currently employed as a data scientist and currently uses of AI agents to expedite code development and documentation. No AI agents and data scientists were harmed in the production of this blog post.

With that preamble, one of the first issues addressed in finance is the agency problem. Before the time value of money, the cost of capital, and the various sources of financing, the risk posed by the diverging interests between shareholders and management is defined. Stated simply, decision makers in any enterprise are the agents of the shareholder, but the interest and incentives of these agents can and will differ from those of the shareholder. Hence, the agency problem: when a manager makes decisions in the interest of him or herself not the shareholders. 

For the shareholder, one potential hope for AI is that the AI agent can be trained to act in their interest alone and have no outside interest or incintive. Saving money and reducing the cost and risk associated with their share would be a useful bonus. Executives are expensive and can be unreliable at crucial times. The shareholder might imagine an agent that will antipate changes to the market place and react to changes effeciently. They imagine an agent who will make the ideal decisions that will maximize their return on investment. Decisions about which products to pursue, how many to make, what price to charge for the product, what suppliers to use, what workers to use, and how much to pay for everything could be optimized by an AI agent rather than executives and that agent could be controlled directly by the shareholders. What could go wrong with an agent making strickly rational decisions on everything? 

The challenge of creating such an AI agent is the massive amounts of data required and the agent would face the same pitfalls of human executives. The amount of variance that can be explained by a statistical model and bias in training data make any optimal target elusive. If all the swans the agent has seen are white, what happens when it sees a black swan? Then, comes the challenge of quantifying the qualitative: is blue a better color than red in a design or logo? Should the shop be a butcher, a baker, or a candlestick maker? Could an AI agent make such a decision? Would an AI agent have decided what consumers really need is a person computer or tablet, the internet or WiFi, rotary phone or smart phone?  

The macro economic challenge agents pose is: if they displace workers in the short term will the firm have customers in the long term. In economic circular flow model, workers earn income in factor markets that flow into households. Households use this income to buy goods and services from markets. Firms earn income by selling to markets and the cycle repeats. Flowing in the opposite direction, the market provides goods and services to households. Those goods and services are transformed into factors that firms use to produce goods and services for the market and so on. Disruptions in the factor market that reduces the households purchasing and ultimately gets passed back to the firm in lower sales. This is not to say that a firm should not use AI or automate to reduce their business costs, but it serves as a warning of the long term risk of these short term gains.

That said, the real challenge with using agents as executives is that the interests of shareholders differ. If one considers investing in corporate America - aka the stock market - he or she will find a variety of investors - the shareholders in the company. New companies have founders heavily invested. Amazon has Jeff Bezos. Meta has Mark Zuckerberg. Microsoft still has Bill Gates. Older companies have the children and grandchildren of founders. Ford has the Ford family. Walmart has the Waltons. For other individual investors like Warren Buffet owning a share of corporate America means either for the regular dividends that come each quarter or the promise of gain on the capital their share represents. Add in institutions like mutual funds and pensions who own stock on behalf of others and you have a diverse set of shareholders with different time horizons and objectives.

A founder's objective might be creating their vision of the future. Henry Ford envisioned a future with a car specifically a Ford in every garage in America. Sam Walton imagined a Walmart in every community in America. Jeff Bezos is imagining a world where autonoumous drones drop off items on a customer's door step and a world of entertainment is available at the click of a button. They often sacrifice immediate profit for growth and market share. For example, Amazon was founded in 1994. It sold its first shares to the public in 1997, and had its first profitable year where its annual revenue exceeded its annual operating cost for the year in 2003. But, it has never paid a dividend to its investors, and yet early investors have received a thousand fold increase in the value of their shares. 

For a founders decendents, their objective might be preserving the founder's legacy by maintaining their vision or collecting dividends on what that vision earns now. For some individual investors, it might be a quick profit so they can spend their remaining days in luxary. For other investors, it might be preserving the capital they have accumulated through a life time of work. These interests inivitably clash: growth or value, regular dividend or one time gains on capital, short term or long term return on investment. Compounding the friction from investors is the friction of what constitutes the best value to the investor. Is a vision of low cost, high through put or a customer centeric approach "best"? Is carrying a wide range of products better than focusing on a narrow range of products? Can AI decide among the competing options or is it better suited to score how closely executive agents match the shareholders vision?
