---
title: "Take on Tanking"
subtitle: "The Case for Middle Tier Expansion of the NBA"
author: "David Price"
date: "2026-06-24"
date-modified: "2026-06-24"
categories: [news, analysis, sports]
---

Can one man can make a difference?

In the sport of basketball, it seems to be the case. It may be a team game where five players on the floor function as one single unit. But, the difference between winning and losing hinges on the performance of one player more so than in any other sport. As a result, many NBA teams have “tanked” - purposefuly lost games by not playing the best players even when available. The best example that comes to my mind is in 1996-1997 season when my beloved San Antonio Spurs tanked. Their best player and my favorite player of all time the Admiral - David Robinson was out for most of the season. He didn't play in the first 18 games due to a preseason back injury. Then, after 6 games, he broke his foot and spent the rest of the season recovering. My beloved Spurs finished 20-62 that season, but won the NBA draft lottery and the option to draft Wake Forest prodigy Tim Duncan. And the rest, they say, is history. 5 championships and 6 trips to the NBA finals over 19 seasons with a winning percentage of 71.0%. 

But, there has been concern that teams with bad records stop playing to win once they realize it is not their year. They sit players, trade expiring contracts, and ask their fanbase to wait until next year. The only buzz they get in the press is in connection to this or that upcoming "generational" talent that will be available in the draft following the season. As the losses pile up, the greater their chances of landing that player becomes and the more hope next year brings to their fans. It also means games that draw fewer fans to their screens and to the arenas.  <Data>

Perhaps instead of fines and the lottery, the solution to "tanking" is to send entire organizations to a lower tier and elevate a proven winners to the NBA with those organizations receiving the top picks. The G League exists in principle now make it work in practice.

There is an existing development league and a number of urban areas that a mid level could be added. Seattle, San Diego, Las Vegas, Austin, Kansas City, St. Louis, Columbus, Cincitani, Pittsburg, Nashville, Baltimore, you get the idea. If you include major cities in Canada, Winnapeg, Edmunton, Calgary, Montreal, and Vancover could also be included. 

My preference would be fewer premier teams and three tiers with 24 teams. That would require 72 locations. 