---
title: "AI and the Artist"
subtitle: "But, is it Art?"
author: "David Price"
date: "2026-07-20"
categories: [analysis, technology, entertainment]
---

This article represents the view of the author and not ChatGPT, Gemini, Claude, Perplexity, or other artifical intelligence composition agents. The only "AI" used in its composition was a spell checker. If what follows offends the aesthetics of the reader, the author acknowledges his background is in natural science not art or its history. His knowledge is limited to a collegic level courses typically taken that explored the arts and humanities, their meaning, and the context of the times they were created. The author is currently employed as a data scientist and uses of AI agents to expedite code development and documentation. Any illustrations included were obtained in electronic form and may or may not have been generated by an AI agent. No AI agents and data scientists were harmed in the production of this blog post, but it represents a questionable advancement in the arts.

The question of using AI confounding creators and composers, artists and illustrators, poets and writers a like is - to paraphrase Syndrone from *The Incredibles*: "When everyone is creative, will anyone be?" Am I the patron or the artist to a work created by an AI agent? Is the sound still music? Are the words still novel or poetic? Does the image or the object still possess beauty? In short, is it art?

Like many things, what something is and its value varies from person to person and generation to generation. Alexander Glazunov dismissed the early work of Igor Stravinsky - questioning if it was even music. Some early criticism included: "Kein Talent, nur Dissonanz" (No Talent, just dissonance). Yet, many today consider Stravinsky's music a needed break from the late Romantic style personafied by Russian composers such as Nikolai Rimsky-Korsakov and Pyotr Tchaikovsky to the modernist style where rhythms became jagged, dissonances became biting, and sound shifts became radical. 

There is l'art pour l'art, the avent garde, where artist press boundaries . But often at limited expense. Paints and brushes, pens and paper, stone and clay. Commerical success was -- and deamed selling out. Will -- when a few golden prompts create an image 

Or, in a commercial sense, if anyone can create anything, who will someone pay to see anyone elses creation?  

I understand Hollywood producers seeking to reduce the size of budgets by switching to new technologies. I understand Hollywood creators seeking to protect their livelihood in the wake of seismic changes to the industry. Perhaps each party grasps: who will want to pay for what others create when a personalized AI agent can create their own story. For creators relying on million dollar salaries that need hundreds of millions from distributing the films to be profitable and be able to make the next movie. Each entertainment dollar directed to personalized content diminishes the budget for the next Hollywood production.

Will we enter a world where entertainment whether video or film is best paraphrased by Winston Churchill: "Never was so much created by so many but viewed by so few"?
